### ISSUE TITLE
【论文复现赛验收】请使用reprod_logger库对齐

### ISSUE THREAD

**Issue by shiyutang** [WangYuanZhiWang/CGNet-paddlepaddle#1]
参照链接：https://github.com/PaddlePaddle/models/blob/develop/docs/ThesisReproduction_CV.md
对网络的前向等进行对齐，对齐后方能验收

**Comment by WangYuanZhiWang** [comment]
> 代码运行出现问题，报错如下： ![image](https://user-images.githubusercontent.com/34859558/138221391-3afba421-d1bc-4afa-89b5-4a1f51dc0061.png)
您好！请您访问新链接https://aistudio.baidu.com/aistudio/projectdetail/2468078?channelType=0&channel=0，选择demo2运行。
您在aistudio上遇到的问题是因为文件夹命名的问题，我直接在源代码里进行了修改，现在您需要做的是：
首先将data文件夹下的dataset.zip 移动到work/CGNet-PP-main/data 文件夹下
然后直接unzip解压
然后命令行运行：python main.py --val 进行测试
或者python main.py --train 进行训练

**Comment by shiyutang** [comment]
验收成功
